name: Cleanup
run-name: "❌ Destroy Infrastructure ${{ github.event.inputs.env_name }} (${{ github.event.inputs.ref }})"
on:
  push:

  # workflow_dispatch:
  #   inputs:
  #     ref:
  #       required: true
  #     env_name:
  #       required: true

concurrency:
  group: ${{ github.run_id }}

jobs:
  destroy_backend:
    name: ❌ Destroy Backend Infrastructure
    runs-on: ubuntu-latest
    steps:
      - run: echo Need to hook up slack here!

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_wrapper: false
        #   terraform_version: 1.2.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Print variables to STDOUT
        run: |
          echo ${{ github.sha }}
          echo ${{ github.run_id }}
          echo ${{ github.event.inputs.ref }}
          # This is a comment

      # - name: Use commit workspace
      #   uses: dflook/terraform-new-workspace@v1
      #   with:
      #     path: util/terraform/backend
      #     workspace: anyhasher-backend-${{ github.event.inputs.ref }}
    
      # - name: Destroy Backend
      #   uses: dflook/terraform-destroy@v1
      #   with:
      #     workspace: anyhasher-backend-${{ github.event.inputs.ref }}
      #     auto_approve: true
      #     path: util/terraform/backend
      #     variables: |
      #       instance_name = "anyhasher-backend-${{ github.event.inputs.ref }}"
    
      - name: Destroy Backend Infrastructure
        id: be_infra
        run: |
          cd util/terraform/backend
          echo "instance_name=\"anyhasher-backend-${{ github.run_number }}\"" >> terraform.tfvars
          terraform init
          terraform destroy -auto-approve

  # cleanup_tag:
  #   name: Clean up the old blue tag
  #   needs: [destroy_backend, destroy_frontend]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Check for old blue tag
  #       uses: mukunku/tag-exists-action@v1.2.0
  #       id: checkTag
  #       with:
  #         tag: "blue/${{ github.event.inputs.ref }}"

  #     - name: Remove old tag
  #       if: steps.checkTag.outputs.exists == 'true'

  #       run: |
  #         git fetch origin
  #         TAG="blue/${{ github.event.inputs.ref }}"
  #         git push --delete origin $TAG

  # notify:
  #   name: Notify team that environment was removed
  #   needs: [cleanup_tag]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo Need to hook up slack here!
